library('ggplot2')
library("grid")
library("readr")

#Aim to make BUSCO comparison plots from the summary files generated by BUSCO

setwd("")   #Set working directiry

# Put all .txt BUSCO result files in one directory so they can be read in together
#Makes a list of all the file names in the directory that are .txt files
files <- list.files(pattern="*.txt", full.names=TRUE, recursive=FALSE)

#A function that takes the busco file and splits the important information out
#returns a vector in the order (complete, single, double, fragment, missing, total)
get_busco_results <- function(busco){
  score <- busco[1,1]
  # complete 
  comp <- unlist(strsplit(score,','))[1]
  compl <- unlist(strsplit(comp,':'))[2]
  complete <- as.numeric(unlist(strsplit(compl,'%'))[1])
  # From complete - single
  sing <- unlist(strsplit(comp,':'))[3]
  single<- as.numeric(unlist(strsplit(sing,'%'))[1])
  
  #From complete - double
  dou<- unlist(strsplit(score,','))[2]
  doub<- unlist(strsplit(dou,':'))[2]
  double<- as.numeric(unlist(strsplit(doub,'%'))[1])
  
  #F is for fragmented
  frag<- unlist(strsplit(score,','))[3]
  fragm<- unlist(strsplit(frag,':'))[2]
  fragment<- as.numeric(unlist(strsplit(fragm,'%'))[1])
  
  #M is for missing
  miss<- unlist(strsplit(score,','))[4]
  missi <- unlist(strsplit(miss,':'))[2]
  missing <- as.numeric(unlist(strsplit(missi,'%'))[1])
  
  #N is for the total
  tot<- unlist(strsplit(score,','))[5]
  tota <- unlist(strsplit(tot,':'))[2]
  total <- as.numeric(unlist(strsplit(tota,'\t'))[1])
  
  
  results <- c(complete, single, double, fragment, missing, total)
  cat <- c('C', 'S', 'D', 'F', 'M', 'T')
  df_result <- cbind(results, cat)
  return(df_result)
}

# Function to get the detailed name
get_details <- function(busco2){
  score <- busco2[1,1]
  #details <- unlist(strsplit(score,'\t'))[2]
  comp <- unlist(strsplit(score,','))[1]
  compl <- unlist(strsplit(comp,':'))[2]
  complete <- as.numeric(unlist(strsplit(compl,'%'))[1])
  #F is for fragmented
  frag<- unlist(strsplit(score,','))[3]
  fragm<- unlist(strsplit(frag,':'))[2]
  fragment<- as.numeric(unlist(strsplit(fragm,'%'))[1])
  #M is for missing
  miss<- unlist(strsplit(score,','))[4]
  missi <- unlist(strsplit(miss,':'))[2]
  missing <- as.numeric(unlist(strsplit(missi,'%'))[1])
  
  details <- paste0('C:', complete, '%, F:',fragment,'%, M:', missing,'%')
  return(details)
}

#Make an empty dataframe which will be filled by the outputs
df_all <- data.frame(results = numeric(0), cat = character(0), sample = character(0), detail = character(0) )

#Take every name in file list, extract sample ID and apply get_busco_results function to the file
#Also apply get_details function for the name. And then output is added to df_all
for (i in files){
  sam <- unlist(strsplit(i,'/'))[2]
  ID <- unlist(strsplit(sam, '_'))[1]

  #read in the file and apply the function
  data <- as.data.frame(read.table(file = i,
                           sep = "\n", dec = ".", header = TRUE))
  output <- as.data.frame(get_busco_results(data))
  output$sample <- ID
  
  #Also 2nd function to get the detailed result
  detailed <- get_details(data)
  output$detail <- detailed
  
  #Add results to df
  df_all <- as.data.frame(rbind(output, df_all))
  }

#Remove the cat 'T = Total, and 'C' complete, because we separate by single or double
df_final <- df_all[df_all$cat != 'T' & df_all$cat != 'C',]
df_final$results <- as.numeric(df_final$results)

#Reorder
df_final$cat = factor(df_final$cat, levels = c("M", "F", "D","S"))
df_final$sample = factor(df_final$sample, levels = c("COSAG2b", "COSAG2a","COSAG1","S15", "S14", "S13","S12","S11","S10","S9","S8","S7", 
                                                  "S6", "S5", "S4", "S3", "S2", "S1"))


#Plot as stacked % bar chart
#Option to print the detailed % break down together, or % per stack
ggplot(df_final, aes( x= sample, y = results, fill =cat)) +
    geom_bar(stat = "identity", width = .6) +
    coord_flip() +
    scale_fill_manual(name = "", values = c("S"="#56B4E9", "D"="#3492C7", "F"="darkgoldenrod2", "M"="brown3"),
                      labels = c("S" = "Complete and single-copy", "D" = "Complete and duplicated",
                                 "F" = "Fragmented", "M" = "Missing")) +
    xlab("Assembly" ) + ylab("%BUSCOs") +
    ggtitle("BUSCO Assessment Results - no plastids") +
    #geom_text(aes(x=sample, y=2, label=detail), size = 3, nudge_x = 0.5,nudge_y =6.5, col="black") +
    geom_text(aes(label = paste0(results,'%')), position = position_stack(vjust = 0.5), size = 3) +
    theme(text= element_text(size=15)) 
                      
              


